#ifndef GUARD_AUTHORIZATION_CONTROL_H
#define GUARD_AUTHORIZATION_CONTROL_H

#include <fltKernel.h>

BOOLEAN is_authorized(_In_ PFLT_CALLBACK_DATA data, _In_ PFLT_FILE_NAME_INFORMATION name_info);

#endif // GUARD_AUTHORIZATION_CONTROL_H