#ifndef GUARD_COMMUNICATION_INFO_H
#define GUARD_COMMUNICATION_INFO_H

#include <ntifs.h>

#define COMMUNICATION_PORT_NAME L"\\CommunicationPort"
#define MAX_FILE_NAME_LENGTH 260
#define POLICY_NUMBER 3
#define MAX_POLICY_COUNT 64

typedef enum {
	OPERATION_TYPE_INVALID = 0,
//	OPERATION_TYPE_CREATE,
	OPERATION_TYPE_DELETE,
	OPERATION_TYPE_FILE_ON_CLOSE,
	OPERATION_TYPE_MOVE,
//	OPERATION_TYPE_READ,
	OPERATION_TYPE_RENAME,
//	OPERATION_TYPE_WRITE,
} OPERATION_TYPE;

typedef enum {
	POLICY_STATUS_NONE = 0,
	POLICY_STATUS_ADD,
	POLICY_STATUS_REMOVE
} POLICY_STATUS;

typedef struct {
	ULONG operation_id;
	BOOLEAN allow;
} USER_RESPONSE;

typedef struct {
	ULONG operation_id;
	UINT16 operation_type;
	WCHAR target_name[MAX_FILE_NAME_LENGTH];
	WCHAR file_name[MAX_FILE_NAME_LENGTH];
} MINIFILTER_REQUEST;

typedef struct {
	UINT8 status;
	ULONG access_mask;
	WCHAR path[MAX_FILE_NAME_LENGTH];
} POLICY;

typedef struct {
	LONG process_id;
	WCHAR installation_path[MAX_FILE_NAME_LENGTH];
	WCHAR local_db_path[MAX_FILE_NAME_LENGTH];
	UINT16 policy_count;
	POLICY* policies;
} USER_INITIAL_CONTEXT;

#endif //GUARD_COMMUNICATION_INFO_H