#ifndef GUARD_COMMUNICATION_INFO_H
#define GUARD_COMMUNICATION_INFO_H

#include <fltKernel.h>

#define COMMUNICATION_PORT_NAME L"\\CommunicationPort"
#define MAX_FILE_NAME_LENGTH 260

typedef enum {
	OPERATION_TYPE_INVALID = 0,
	OPERATION_TYPE_CREATE,
	OPERATION_TYPE_CLEANUP,
	OPERATION_TYPE_CLOSE,
	OPERATION_TYPE_DELETE,
	OPERATION_TYPE_DIRECTORY_CONTROL,
	OPERATION_TYPE_FILE_ON_CLOSE,
	OPERATION_TYPE_MOVE,
	OPERATION_TYPE_READ,
	OPERATION_TYPE_RENAME,
	OPERATION_TYPE_SET_SECURITY,
	OPERATION_TYPE_QUERY_INFORMATION,
	OPERATION_TYPE_QUERY_SECURITY,
	OPERATION_TYPE_WRITE,
} OPERATION_TYPE;

typedef struct {
	ULONG operation_id;
	BOOLEAN allow;
} USER_REPLY;

typedef struct {
	ULONG operation_id;
	UINT16 operation_type;
	WCHAR target_name[260];
	WCHAR file_name[260];
} CONFIRMATION_MESSAGE;

typedef struct {
	ULONG token;
	LONG process_id;
	WCHAR path[256];
} USER_PROCESS_INFO;

#endif //GUARD_COMMUNICATION_INFO_H